/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.DB;
import com.alee.laf.WebLookAndFeel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Danushka
 */
public class AddBooking extends javax.swing.JFrame {

    /**
     * Creates new form Sample
     */
    private static String bookno;

    public AddBooking() {
        initComponents();
        date_time();
        setRoom();
        setCus();

        jButton1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        days = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        room = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cus = new javax.swing.JComboBox();
        start = new com.alee.extended.date.WebDateField();
        jLabel6 = new javax.swing.JLabel();
        end = new com.alee.extended.date.WebDateField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hotel Hilro - Balalngoda");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Select Room");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 80, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hotel.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 450, 540));

        days.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                daysKeyTyped(evt);
            }
        });
        getContentPane().add(days, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 200, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Days");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 60, 20));

        room.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC Room", "Non AC Room" }));
        getContentPane().add(room, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 200, 30));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Start Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 70, 20));

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 70, -1));

        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 70, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Book Room");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 27));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Customer");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 80, 20));

        cus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single Bed", "Double Bed" }));
        getContentPane().add(cus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, 30));
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 200, 30));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("End Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 70, 20));
        getContentPane().add(end, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 200, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String ro = room.getSelectedItem().toString().split("-")[0];
        String cs = cus.getSelectedItem().toString().split("-")[0];
        String day = days.getText();
        String st = start.getText();
        String ed = end.getText();

        if (!(days.getText().isEmpty()&&start.getText().isEmpty()&&end.getText().isEmpty())) {
            try {
            DB.idu("INSERT INTO `hotel`.`bookingtable` (`room_no`, `cus_no`, `date_fro`, `date_to`, `no_of_day`) VALUES ('"
                    + ro + "', '" + cs + "', '" + st + "', '" + ed + "', '" + day + "');");
            days.setText(null);
            start.setText(null);
            
            end.setText(null);
            cus.setSelectedIndex(0);
            room.setSelectedIndex(0);
            room.grabFocus();

        } catch (Exception ex) {
            Logger.getLogger(AddBooking.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }else{
        
            JOptionPane.showMessageDialog(null, "Fill all feilds");
            
        }
        
       

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void daysKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_daysKeyTyped
         char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_PERIOD)) {

            evt.consume();

        }
    }//GEN-LAST:event_daysKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        WebLookAndFeel.install();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox cus;
    private static javax.swing.JTextField days;
    private static com.alee.extended.date.WebDateField end;
    private static javax.swing.JButton jButton1;
    private static javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JComboBox room;
    private static com.alee.extended.date.WebDateField start;
    // End of variables declaration//GEN-END:variables

    public void date_time() {
        Timer t = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                java.util.Date date = new java.util.Date();
                SimpleDateFormat simpleDateFormat = new SimpleDateFormat("YYYY/MMM/dd - h:mm:ss a");
//                txtDate.setText(simpleDateFormat.format(date));

            }
        });
        t.start();

    }

    public static void updateroom(String bookno1) {
        
       

    }

    private void setRoom() {

        try {
            ResultSet rs = DB.search("Select * from roomdetail");

            DefaultComboBoxModel dcm = new DefaultComboBoxModel();
            dcm.removeAllElements();
            while (rs.next()) {

                dcm.addElement(rs.getString("room_no") + "-" + rs.getString("room_type") + "-" + rs.getString("room_bed"));

            }

            room.setModel(dcm);

        } catch (Exception ex) {
            Logger.getLogger(AddBooking.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void setCus() {
        try {
            ResultSet rs = DB.search("Select * from custdetail");

            DefaultComboBoxModel dcm = new DefaultComboBoxModel();
            dcm.removeAllElements();

            while (rs.next()) {

                dcm.addElement(rs.getString("Cust_id_no") + "-" + rs.getString("Cust_name"));

            }

            cus.setModel(dcm);

        } catch (Exception ex) {
            Logger.getLogger(AddBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
