/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.DB;
import com.alee.laf.WebLookAndFeel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Danushka
 */
public class ViewRoom extends javax.swing.JFrame {

    /**
     * Creates new form Sample
     */
    
    DecimalFormat dcf = new DecimalFormat("#######.00");
    
    public ViewRoom() {
        initComponents();
        loadroom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboroomtype = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        comboBed = new javax.swing.JComboBox();
        btnbed = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnRoomt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableroom = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hotel Hilro - Balalngoda");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Room Type");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tasks.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 300, 540));

        comboroomtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC Room", "Non AC Room" }));
        getContentPane().add(comboroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 200, 30));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Room Type");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 80, 20));

        comboBed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single Bed", "Double Bed" }));
        getContentPane().add(comboBed, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 200, 30));

        btnbed.setText("Find");
        btnbed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbedActionPerformed(evt);
            }
        });
        getContentPane().add(btnbed, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 70, 30));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("View Room");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 27));

        btnRoomt.setText("Find");
        btnRoomt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomtActionPerformed(evt);
            }
        });
        getContentPane().add(btnRoomt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 70, 30));

        tableroom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Room No", "Type", "Bed", "Rate"
            }
        ));
        jScrollPane1.setViewportView(tableroom);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 270));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 80, -1));

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, -1, -1));

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 70, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbedActionPerformed
        
        try {
            ResultSet rs = DB.search("SELECT * from roomdetail WHERE room_bed = '"+comboBed.getSelectedItem()+"'");
             DefaultTableModel dtm = (DefaultTableModel) tableroom.getModel();
            dtm.setRowCount(0);
            
            while (rs.next()) {                
                
                dtm.addRow(new Object[]{rs.getString("room_id"), rs.getString("room_no"), rs.getString("room_type"), rs.getString("room_bed"), dcf.format(rs.getDouble("room_rate")) });
                
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnbedActionPerformed

    private void btnRoomtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomtActionPerformed
        try {
            ResultSet rs = DB.search("SELECT * from roomdetail WHERE room_type = '"+comboroomtype.getSelectedItem()+"'");
             DefaultTableModel dtm = (DefaultTableModel) tableroom.getModel();
            dtm.setRowCount(0);
            
            while (rs.next()) {                
                
                dtm.addRow(new Object[]{rs.getString("room_id"), rs.getString("room_no"), rs.getString("room_type"), rs.getString("room_bed"), dcf.format(rs.getDouble("room_rate")) });
                
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRoomtActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       
        try {
            
            DB.idu("DELETE FROM roomdetail WHERE room_id = '"+tableroom.getValueAt(tableroom.getSelectedRow(), 0)+"'");
            loadroom();
        } catch (Exception ex) {
            Logger.getLogger(ViewRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        new AddRoom().setVisible(true);
        AddRoom.updateroom(tableroom.getValueAt(tableroom.getSelectedRow(), 0).toString());
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        
        try {
            tableroom.print(JTable.PrintMode.NORMAL);
        } catch (PrinterException ex) {
            Logger.getLogger(ViewRoom.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     WebLookAndFeel.install();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRoomt;
    private javax.swing.JButton btnbed;
    private javax.swing.JComboBox comboBed;
    private javax.swing.JComboBox comboroomtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableroom;
    // End of variables declaration//GEN-END:variables

     public void date_time() {
        Timer t = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                java.util.Date date = new java.util.Date();
                SimpleDateFormat simpleDateFormat = new SimpleDateFormat("YYYY/MMM/dd - h:mm:ss a");
//                txtDate.setText(simpleDateFormat.format(date));

            }
        });
        t.start();

    }

    private void loadroom() {
       
        try {
            ResultSet rs = DB.search("SELECT * FROM roomdetail");
            DefaultTableModel dtm = (DefaultTableModel) tableroom.getModel();
            dtm.setRowCount(0);
            
            while (rs.next()) {                
                
                dtm.addRow(new Object[]{rs.getString("room_id"), rs.getString("room_no"), rs.getString("room_type"), rs.getString("room_bed"), dcf.format(rs.getDouble("room_rate")) });
                
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

}
