/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.DB;
import com.alee.laf.WebLookAndFeel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Danushka
 */
public class ViewBooking extends javax.swing.JFrame {

    /**
     * Creates new form Sample
     */
    DecimalFormat dcf = new DecimalFormat("#######.00");

    public ViewBooking() {
        initComponents();
        loadcs();
        setRoom();
        setCus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableroom = new javax.swing.JTable();
        cusN = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        roomN = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btnRoomt = new javax.swing.JButton();
        btnbed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hotel Hilro - Balalngoda");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tasks.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 300, 540));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("View Booking");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 27));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 80, -1));

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 70, -1));

        tableroom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Room", "Customer", "Days", "Start", "End"
            }
        ));
        jScrollPane1.setViewportView(tableroom);
        if (tableroom.getColumnModel().getColumnCount() > 0) {
            tableroom.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 520, 290));

        cusN.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single Bed", "Double Bed" }));
        getContentPane().add(cusN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, 30));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Customer");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 80, 20));

        roomN.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC Room", "Non AC Room" }));
        getContentPane().add(roomN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 200, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Select Room");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 80, 20));

        btnRoomt.setText("Find");
        btnRoomt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomtActionPerformed(evt);
            }
        });
        getContentPane().add(btnRoomt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 70, 30));

        btnbed.setText("Find");
        btnbed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbedActionPerformed(evt);
            }
        });
        getContentPane().add(btnbed, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 70, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        try {

            DB.idu("DELETE FROM bookingtable WHERE book_id = '" + tableroom.getValueAt(tableroom.getSelectedRow(), 0) + "'");
            loadcs();
        } catch (Exception ex) {
            Logger.getLogger(ViewBooking.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            tableroom.print(JTable.PrintMode.NORMAL);
        } catch (PrinterException ex) {
            Logger.getLogger(ViewBooking.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnRoomtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomtActionPerformed
        try {
            ResultSet rs = DB.search("SELECT bookingtable.*, custdetail.Cust_name FROM bookingtable INNER JOIN custdetail ON bookingtable.cus_no = custdetail.Cust_id_no WHERE bookingtable.room_no = '" + roomN.getSelectedItem().toString().split("-")[0] + "'");

//            ResultSet rs = DB.search("SELECT * FROM bookingtable WHERE room_no = '" + roomN.getSelectedItem().toString().split("-")[0] + "'");
            DefaultTableModel dtm = (DefaultTableModel) tableroom.getModel();
            dtm.setRowCount(0);

            while (rs.next()) {

                dtm.addRow(new Object[]{rs.getString("book_id"), rs.getString("room_no"), rs.getString("Cust_name"), rs.getString("no_of_day"), rs.getString("date_fro"), rs.getString("date_to")});

            }
        } catch (Exception ex) {
            Logger.getLogger(ViewRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRoomtActionPerformed

    private void btnbedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbedActionPerformed

        try {
            
            ResultSet rs = DB.search("SELECT bookingtable.*, custdetail.Cust_name FROM bookingtable INNER JOIN custdetail ON bookingtable.cus_no = custdetail.Cust_id_no WHERE bookingtable.cus_no = '" + cusN.getSelectedItem().toString().split("-")[0] + "'");
            
            DefaultTableModel dtm = (DefaultTableModel) tableroom.getModel();
            dtm.setRowCount(0);

            while (rs.next()) {

                dtm.addRow(new Object[]{rs.getString("book_id"), rs.getString("room_no"), rs.getString("Cust_name"), rs.getString("no_of_day"), rs.getString("date_fro"), rs.getString("date_to")});

            }
        } catch (Exception ex) {
            Logger.getLogger(ViewRoom.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnbedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        WebLookAndFeel.install();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRoomt;
    private javax.swing.JButton btnbed;
    public static javax.swing.JComboBox cusN;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JComboBox roomN;
    private javax.swing.JTable tableroom;
    // End of variables declaration//GEN-END:variables

    public void date_time() {
        Timer t = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                java.util.Date date = new java.util.Date();
                SimpleDateFormat simpleDateFormat = new SimpleDateFormat("YYYY/MMM/dd - h:mm:ss a");
//                txtDate.setText(simpleDateFormat.format(date));

            }
        });
        t.start();

    }

    private void loadcs() {

        try {
            ResultSet rs = DB.search("SELECT bookingtable.*, custdetail.Cust_name FROM bookingtable INNER JOIN custdetail ON bookingtable.cus_no = custdetail.Cust_id_no");
            DefaultTableModel dtm = (DefaultTableModel) tableroom.getModel();
            dtm.setRowCount(0);

            while (rs.next()) {

                dtm.addRow(new Object[]{rs.getString("book_id"), rs.getString("room_no"), rs.getString("Cust_name"), rs.getString("no_of_day"), rs.getString("date_fro"), rs.getString("date_to")});

            }
        } catch (Exception ex) {
            Logger.getLogger(ViewBooking.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void setRoom() {

        try {
            ResultSet rs = DB.search("Select * from roomdetail");

            DefaultComboBoxModel dcm = new DefaultComboBoxModel();
            dcm.removeAllElements();
            while (rs.next()) {

                dcm.addElement(rs.getString("room_no") + "-" + rs.getString("room_type") + "-" + rs.getString("room_bed"));

            }

            roomN.setModel(dcm);

        } catch (Exception ex) {
            Logger.getLogger(AddBooking.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void setCus() {
        try {
            ResultSet rs = DB.search("Select * from custdetail");

            DefaultComboBoxModel dcm = new DefaultComboBoxModel();
            dcm.removeAllElements();

            while (rs.next()) {

                dcm.addElement(rs.getString("Cust_id_no") + "-" + rs.getString("Cust_name"));

            }

            cusN.setModel(dcm);

        } catch (Exception ex) {
            Logger.getLogger(AddBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
